--liquibase formatted sql
--changeset mpernal:01 endDelimiter:GO
CREATE TABLE IF NOT EXISTS APP_USER (
    ID  bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    USERNAME varchar(255) NOT NULL,
    HASHED_PASSWORD varchar(255) NOT NULL,
    SALT varchar(255) NOT NULL,
    EMAIL varchar(255) NOT NULL,
    CONSTRAINT email_unique UNIQUE(EMAIL),
    CONSTRAINT username_unique UNIQUE(USERNAME)
    )
GO

--liquibase formatted sql
--changeset mpernal:02 endDelimiter:GO
    INSERT INTO APP_USER(USERNAME, EMAIL, HASHED_PASSWORD,SALT)
    VALUES ('exomat', 'exomat@wp.pl', 'te','te')
    GO